FROM public.ecr.aws/lambda/python:3.9

COPY ./fornecedorlog ./fornecedorlog
COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r ./requirements.txt

CMD ["fornecedorlog.api.handler"]