apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fornecedorlog
  name: fornecedorlog
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fornecedorlog
  type: LoadBalancer
status:
  loadBalancer: {}
